services:
  traefik:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      development:
    volumes:
      # Mount the Docker socket as read-only so Traefik can listen to events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.infrastructure/conf/traefik/dev/traefik.yml:/traefik.yml:ro
      - ./.infrastructure/conf/traefik/dev/traefik-certs.yml:/traefik-certs.yml
      - ./.infrastructure/conf/traefik/dev/certificates/:/certificates

  php:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
    volumes:
      - ./:/var/www/html/
    networks:
      - development
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`codewithkyrian.local`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.http.services.backend.loadbalancer.server.scheme=http"

  bun:
    image: 'oven/bun:alpine'
    volumes:
      - ./:/home/bun/app
    ports:
      - "5173:5173"
    command: sh -c "bun install && bun run dev"
    networks:
      - development

  mailpit:
    image: axllent/mailpit
    networks:
      - development
    ports:
      - "8025:8025"

networks:
  development:
