version: '3.8'
services:

  app:
    build:
      context: .
      target: ci
    networks:
      - ci
    volumes:
      - .:/var/www/html/
    working_dir: /var/www/html/
    environment:
      AUTORUN_ENABLED: false

  bun:
    image: 'oven/bun:alpine'
    volumes:
      - ./:/home/bun/app:cached
    working_dir: /home/bun/app/
    networks:
      - ci

networks:
  ci: