FROM oven/bun:1.2.4-alpine AS frontend-build

# Set working directory
WORKDIR /app

# Copy application code
COPY . .

# Build frontend assets
RUN bun install && \
    bun run build



# Main image
FROM richarvey/nginx-php-fpm:3.1.6

# Copy application code
COPY . .
#HR>BA9|6s

# Copy built assets from frontend build stage
COPY --from=frontend-build /app/public/build/ /var/www/html/public/build/

# Image config
ENV SKIP_COMPOSER 1
ENV WEBROOT /var/www/html/public
ENV PHP_ERRORS_STDERR 1
ENV RUN_SCRIPTS 1
ENV REAL_IP_HEADER 1

# Laravel config
ENV APP_NAME "CodeWithKyrian"
ENV LOG_CHANNEL stderr

# Allow composer to run as root
ENV COMPOSER_ALLOW_SUPERUSER 1

CMD ["/start.sh"]
