name: Deploy to Shared
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build & Deploy Assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm install

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Compile assets
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          echo "
              HostKeyAlgorithms +ssh-rsa
              PubkeyAcceptedAlgorithms +ssh-rsa" > ~/.ssh/config
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -p 65002 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run Deploy Script
        run: |
          ssh u461887068@${{ secrets.SERVER_IP }} -p 65002 'bash -s' < ${{ github.workspace }}/.github/workflows/deploy.sh

      - name: Sync Public Directory
        run: |
          rsync -rv --rsh="ssh -p 65002" ${{ github.workspace }}/public/ u461887068@${{ secrets.SERVER_IP }}:domains/codewithkyrian.com/public_html
          rsync -rv --rsh="ssh -p 65002" ${{ github.workspace }}/public/build/ u461887068@${{ secrets.SERVER_IP }}:domains/codewithkyrian.com/public/build
